### ISSUE TITLE
All objects being destroyed and recreated when moving to unified NAC ACI module from pre-unified NAC ACI comprehensive example

### ISSUE THREAD

**Issue by xfire99** [netascode/nac-aci-comprehensive-example#2]
When updating from the pre-unified comprehensive example to the unified NAC ACI comprehensive, all objects are wanting to be destroyed and then re-created due to the movement of the module calls.  Would it be possible to account for this refactoring and incorporate the appropriate move statements so that objects would not have to be destroyed and then re-created when updating to latest version?  

Or is there another workaround to prevent full object destruction and then recreation?

**Comment by danischm** [comment]
The easiest is to re-apply the config with the non-unified modules to ensure there are no pending changes, then delete the state and re-deploy with the unified module. The procedure is documented here: https://developer.cisco.com/docs/nexus-as-code/#!unified-module-migration/migration

**Comment by xfire99** [comment]
Thanks for the quick response.  I'll take a look at that.

**Comment by robvand** [comment]
Closing issue after migration steps being provided.
